AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: slack slash command for amesh

Parameters:
  SlackSigningSecret:
    Type: String
    Description: Slack Signing Secret for request verification

Resources:
  AmeshSlackCommand:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: package.zip
      Handler: slackhandler.lambda_handler
      Runtime: python3.12
      Timeout: 10
      MemorySize: 1024
      Environment:
        Variables:
          SLACK_SIGNING_SECRET: !Ref SlackSigningSecret
      FunctionUrlConfig:
        AuthType: NONE
        Cors:
          AllowOrigins:
            - '*'
          AllowMethods:
            - POST
          AllowHeaders:
            - content-type
            - x-slack-signature
            - x-slack-request-timestamp
